server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://${LOCAL_HOST}:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://${LOCAL_HOST}:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://${LOCAL_HOST}:5000
    cart:
      path: /cart/**
      url: http://${LOCAL_HOST}:1004/api/v1
